=== dooobob/json-schema-app/public/json/pms/item.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "_id": {
      "title": "품목 ID",
      "type": "string"
    },
    "ori_id": {
      "title": "품목 부모 ID",
      "type": "string"
    },
    "created_by": {
      "title": "작성자",
      "type": "string"
    },
    "updated_by": {
      "title": "수정자",
      "type": "string"
    },
    "created_at": {
      "title": "작성일시",
      "type": "string"
    },
    "updated_at": {
      "title": "수정일시",
      "type": "string"
    },
    "version": {
      "title": "버전",
      "type": "integer"
    },
    "saved": {
      "title": "저장수",
      "type": "integer"
    },
    "latest": {
      "title": "최신",
      "type": "boolean"
    },
    "active": {
      "title": "활성",
      "type": "boolean"
    },
    "basic_info": {
      "title": "기본 정보",
      "type": "object",
      "properties": {
        "item_name": {
          "title": "품목명",
          "type": "string"
        },
        "distinction": {
          "title": "재고구분",
          "type": "string"
        },
        "classification": {
          "title": "품목분류",
          "type": "string"
        },
        "type": {
          "title": "품목타입",
          "type": "string"
        },
        "cost": {
          "title": "제작단가",
          "type": "integer"
        },
        "price": {
          "title": "판매단가",
          "type": "integer"
        },
        "quantity": {
          "title": "세트수",
          "type": "integer"
        },
        "file_name": {
          "title": "파일명",
          "type": "string"
        },
        "file_url": {
          "title": "url",
          "type": "string"
        },
        "location": {
          "title": "위치",
          "type": "string"
        },
        "note": {
          "title": "메모",
          "type": "string"
        },
        "check": {
          "title": "검수",
          "type": "string"
        },
        "shop": {
          "title": "발주처",
          "type": "object",
          "properties": {
            "shop_id": {
              "title": "발주처 ID",
              "type": "string"
            },
            "shop_name": {
              "title": "발주처 이름",
              "type": "string"
            }
          },
          "required": [
            "shop_id",
            "shop_name"
          ]
        }
      },
      "required": [
        "item_name",
        "distinction",
        "classification",
        "type",
        "cost",
        "price",
        "quantity",
        "file_name",
        "file_url",
        "location",
        "note",
        "check",
        "shop"
      ]
    },
    "components": {
      "title": "상세항목",
      "type": "array",
      "items": [{
        "type": "object",
        "properties": {
          "_id": {
            "title": "소품목 ID",
            "type": "string"
          },
          "component_name": {
            "title": "소품목 이름",
            "type": "string"
          },
          "volume": {
            "title": "종",
            "type": "integer"
          },
          "quantity": {
            "title": "수량",
            "type": "integer"
          },
          "stock": {
            "title": "재고",
            "type": "integer"
          },
          "demand": {
            "title": "주문",
            "type": "integer"
          },
          "order": {
            "title": "발주",
            "type": "integer"
          },
          "size": {
            "title": "사이즈",
            "type": "string"
          },
          "note": {
            "title": "특이사항",
            "type": "string"
          },
          "spec": {
            "title": "제품사양",
            "type": "object",
            "properties": {
              "spec_id": {
                "title": "spec id",
                "type": "string"
              },
              "spec_code": {
                "title": "spec code",
                "type": "string"
              },
              "classification_code": {
                "title": "분류 code",
                "type": "string"
              },
              "code_index": {
                "title": "코드 인덱스",
                "type": "integer"
              },
              "material": {
                "title": "재질",
                "type": "string"
              },
              "print": {
                "title": "인쇄",
                "type": "string"
              },
              "processing": {
                "title": "가공",
                "type": "string"
              }
            },
            "required": [
              "spec_id",
              "spec_code",
              "classification_code",
              "code_index",
              "material",
              "print",
              "processing"
            ]
          }
        },
        "required": [
          "_id",
          "component_name",
          "volume",
          "quantity",
          "stock",
          "demand",
          "order",
          "size",
          "note",
          "spec"
        ]
      }]
    }
  },
  "required": [
    "_id",
    "ori_id",
    "created_by",
    "updated_by",
    "created_at",
    "updated_at",
    "version",
    "saved",
    "latest",
    "active",
    "basic_info",
    "components"
  ]
}

=== dooobob/json-schema-app/public/json/pms/item.json
{
    "_id": "",
    "ori_id": "",
    "created_by": "",
    "updated_by": "",
    "created_at": "",
    "updated_at": "",
    "version": 0,
    "saved": 0,
    "latest": false,
    "active": false,
    "basic_info": {
        "item_name": "",
        "distinction": "",
        "classification": "",
        "type": "",
        "cost": 0,
        "price": 0,
        "quantity": 1,
        "file_name": "",
        "file_url": "",
        "location": "",
        "note": "",
        "check": "",
        "shop": {
            "shop_id": "",
            "shop_name": ""
        }
    },
    "components": [{
        "_id": "",
        "component_name": "",
        "volume": 0,
        "quantity": 0,
        "stock": 0,
        "demand": 0,
        "order": 0,
        "size": "",
        "note": "",
        "spec": {
            "spec_id": "",
            "spec_code": "",
            "classification_code": "",
            "code_index": 0,
            "material": "",
            "print": "",
            "processing": ""
        }
    }]
}
