=== dooobob/json-schema-app/public/json/coo/evaluation_client_v2.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "location": {
            "title": "사고위치",
            "type": "string"
        },
        "accident": {
            "title": "사고상황",
            "type": "string"
        },
        "casualties_count": {
            "title": "사상자 수",
            "type": "integer"
        },
        "select_triage_type": {
            "title": "트리아지 타입",
            "type": "string"
        },
        "triage_accuracy": {
            "title": "분류 정확도 점수",
            "type": "number"
        },
        "aid_accuracy": {
            "title": "처치 적합성 점수",
            "type": "number"
        },
        "aid_priority": {
            "title": "처치 우선도 점수",
            "type": "number"
        },
        "aid_perfect": {
            "title": "처치 만점 여부",
            "type": "boolean"
        },
        "over_triage": {
            "title": "상향분류수",
            "type": "integer"
        },
        "under_triage": {
            "title": "하향분류수",
            "type": "integer"
        },
        "gcs_accuracy": {
            "title": "gcs 정확도 점수",
            "type": "number"
        },
        "gcs_correct": {
            "title": "gcs 정답수",
            "type": "integer"
        },
        "patient_feedbacks": {
            "title": "환자평가",
            "type": "array",
            "items": [{
                "type": "object",
                "properties": {
                    "good_triage": {
                        "title": "적합분류(정답)",
                        "type": "string"
                    },
                    "selected_triage": {
                        "title": "선택한분류",
                        "type": "string"
                    },
                    "good_gcs": {
                        "title": "반응여부",
                        "type": "object",
                        "properties": {
                            "eye_opening": {
                                "title": "개안반응",
                                "type": "integer"
                            },
                            "verbal": {
                                "title": "언어반응",
                                "type": "integer"
                            },
                            "motor": {
                                "title": "운동반응",
                                "type": "integer"
                            }
                        },
                        "required": [
                            "eye_opening",
                            "verbal",
                            "motor"
                        ]
                    },
                    "selected_gcs": {
                        "title": "반응여부",
                        "type": "object",
                        "properties": {
                            "eye_opening": {
                                "title": "개안반응",
                                "type": "integer"
                            },
                            "verbal": {
                                "title": "언어반응",
                                "type": "integer"
                            },
                            "motor": {
                                "title": "운동반응",
                                "type": "integer"
                            }
                        },
                        "required": [
                            "eye_opening",
                            "verbal",
                            "motor"
                        ]
                    },
                    "aid_time": {
                        "title": "처음 처치한 시각",
                        "type": "integer"
                    },
                    "name": {
                        "title": "환자이름",
                        "type": "string"
                    },
                    "gender": {
                        "title": "환자성별",
                        "type": "string"
                    },
                    "age": {
                        "title": "환자나이",
                        "type": "number"
                    },
                    "comments": {
                        "title": "코멘트목록",
                        "type": "array",
                        "items": [{
                            "title": "코멘트",
                            "type": "string"
                        }]
                    }
                },
                "required": [
                    "good_triage",
                    "selected_triage",
                    "good_gcs",
                    "selected_gcs",
                    "aid_time",
                    "name",
                    "gender",
                    "age",
                    "comments"
                ]
            }]
        }
    },
    "required": [
        "location",
        "accident",
        "casualties_count",
        "select_triage_type",
        "triage_accuracy",
        "aid_accuracy",
        "aid_priority",
        "aid_perfect",
        "over_triage",
        "under_triage",
        "gcs_accuracy",
        "gcs_correct",
        "patient_feedbacks"
    ]
}

=== dooobob/json-schema-app/public/json/coo/evaluation_client_v2.json
{
    "location": "",
    "accident": "",
    "casualties_count": 0,
    "select_triage_type": "",
    "triage_accuracy": 0.0,
    "aid_accuracy": 0.0,
    "aid_priority": 0.0,
    "aid_perfect": false,
    "over_triage": 0,
    "under_triage": 0,
    "gcs_accuracy": 0.0,
    "gcs_correct": 0,
    "patient_feedbacks": [{
        "good_triage": "",
        "selected_triage": "",
        "good_gcs": {
            "eye_opening": 4,
            "verbal": 5,
            "motor": 6
        },
        "selected_gcs": {
            "eye_opening": 4,
            "verbal": 5,
            "motor": 6
        },
        "aid_time": 0,
        "name": "",
        "gender": "",
        "age": 0.0,
        "comments": [""]
    }]
}
