=== dooobob/json-schema-app/public/json/coo/scenario.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "channel_num": {
            "title": "채널 번호",
            "type": "integer"
        },
        "created_by": {
            "title": "생성자",
            "type": "string"
        },
        "created_at": {
            "title": "생성일시",
            "type": "integer"
        },
        "updated_by": {
            "title": "수정자",
            "type": "string"
        },
        "updated_at": {
            "title": "수정일시",
            "type": "integer"
        },
        "single_mode": {
            "title": "훈련모드",
            "type": "boolean"
        },
        "scenario_name": {
            "title": "방 이름",
            "type": "string"
        },
        "location": {
            "title": "사고위치",
            "type": "string"
        },
        "accident": {
            "title": "사고상황",
            "type": "string"
        },
        "casualties_count": {
            "title": "사상자수",
            "type": "integer"
        },
        "scenario_state": {
            "title": "시나리오상태",
            "type": "string"
        },
        "playing_state": {
            "title": "훈련상태",
            "type": "boolean"
        },
        "play_time": {
            "title": "진행시간",
            "type": "integer"
        },
        "start_time": {
            "title": "시작시간",
            "type": "integer"
        },
        "end_time": {
            "title": "종료시간",
            "type": "integer"
        },
        "pause": {
            "title": "멈춤",
            "type": "array",
            "items": [{
                "time": {
                    "title": "멈춤시간",
                    "type": "integer"
                }
            }]
        },
        "resume": {
            "title": "재시작",
            "type": "array",
            "items": [{
                "time": {
                    "title": "재시작시간",
                    "type": "integer"
                }
            }]
        },
        "participants": {
            "title": "참가자 목록",
            "type": "array",
            "items": [{
                "title": "참가자",
                "type": "object",
                "properties": {
                    "user_email": {
                        "title": "사용자아이디",
                        "type": "string"
                    },
                    "nickname": {
                        "title": "별명",
                        "type": "string"
                    },
                    "role": {
                        "title": "역할",
                        "type": "string"
                    },
                    "triage_method": {
                        "title": "트리아지 방법",
                        "type": "string"
                    },
                    "level": {
                        "title": "참가자 권한",
                        "type": "integer"
                    },
                    "evaluation": {
                        "title": "평가 데이터",
                        "type": "object"
                    }
                }
            }]
        },
        "patients": {
            "type": "array",
            "title": "환자데이터",
            "items": [{
                "title": "환자",
                "type": "string"
            }]
        }
    }
}

=== dooobob/json-schema-app/public/json/coo/scenario.json
{
    "channel_num": 0,
    "created_by": "",
    "created_at": 0,
    "updated_by": "",
    "updated_at": 0,
    "single_mode": true,
    "scenario_name": "",
    "location": "",
    "accident": "",
    "casualties_count": 0,
    "scenario_state": "",
    "playing_state": false,
    "play_time": 0,
    "start_time": 0,
    "end_time": 0,
    "pause": [0],
    "resume": [0],
    "participants": [{
        "user_email": "",
        "nickname": "",
        "role": "",
        "triage_method": "",
        "level": 0,
        "evaluation": {}
    }],
    "patients": [""]
}
