=== dooobob/json-schema-app/public/json/item.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "item_id": {
      "title": "품목 id",
      "type": "string"
    },
    "created_by": {
      "title": "작성자",
      "type": "string"
    },
    "updated_by": {
      "title": "수정자",
      "type": "string"
    },
    "created_at": {
      "title": "작성일시",
      "type": "string"
    },
    "updated_at": {
      "title": "수정일시",
      "type": "string"
    },
    "version": {
      "title": "버전",
      "type": "string"
    },
    "basic_info": {
      "type": "object",
      "title": "기본정보",
      "properties": {
        "item_name": {
          "title": "품목명",
          "type": "string"
        },
        "usage": {
          "title": "사용유형",
          "type": "string"
        },
        "category": {
          "title": "카테고리",
          "type": "string"
        },
        "note": {
          "title": "메모",
          "type": "string"
        }
      },
      "required": [
        "item_name",
        "usage",
        "category",
        "note"
      ]
    },
    "contents": {
      "title": "구성품 목록",
      "type": "array",
      "items": [{
        "title": "구성품",
        "type": "object",
        "properties": {
          "content_id": {
            "title": "구성품 id",
            "type": "string"
          },
          "content_index": {
            "title": "구성품 순번",
            "type": "string"
          },
          "content_name": {
            "title": "구성품명",
            "type": "string"
          },
          "note": {
            "title": "특이사항",
            "type": "string"
          },
          "volume": {
            "title": "권장량",
            "type": "integer"
          },
          "stock": {
            "title": "재고",
            "type": "integer"
          },
          "created_by": {
            "title": "작성자",
            "type": "string"
          },
          "updated_by": {
            "title": "수정자",
            "type": "string"
          },
          "created_at": {
            "title": "작성일시",
            "type": "string"
          },
          "updated_at": {
            "title": "수정일시",
            "type": "string"
          },
          "hidden": {
            "title": "숨김",
            "type": "boolean"
          },
          "spec": {
            "title": "제품사양",
            "type": "object",
            "properties": {
              "_id": {
                "title": "object id",
                "type": "string"
              },
              "spec_code": {
                "title": "spec code",
                "type": "string"
              },
              "custom": {
                "title": "커스텀",
                "type": "boolean"
              },
              "description": {
                "title": "설명",
                "type": "string"
              },
              "width": {
                "title": "가로",
                "type": "string"
              },
              "height": {
                "title": "세로",
                "type": "string"
              },
              "depth": {
                "title": "높이",
                "type": "string"
              },
              "material": {
                "title": "재질",
                "type": "string"
              },
              "print": {
                "title": "인쇄",
                "type": "string"
              },
              "processing": {
                "title": "가공",
                "type": "string"
              },
              "cost": {
                "title": "제작단가",
                "type": "integer"
              },
              "duration": {
                "title": "소요기간",
                "type": "integer"
              },
              "note": {
                "title": "비고",
                "type": "string"
              },
              "version": {
                "title": "버전",
                "type": "integer"
              },
              "shop": {
                "title": "거래처",
                "type": "object",
                "properties": {
                  "shop_id": {
                    "title": "거래처 id",
                    "type": "string"
                  },
                  "shop_name": {
                    "title": "거래처 이름",
                    "type": "string"
                  }
                },
                "required": [
                  "shop_id",
                  "shop_name"
                ]
              }
            },
            "required": [
              "_id",
              "spec_code",
              "custom",
              "description",
              "width",
              "height",
              "depth",
              "material",
              "print",
              "processing",
              "cost",
              "duration",
              "note",
              "version",
              "shop"
            ]
          }
        },
        "required": [
          "content_id",
          "content_index",
          "content_name",
          "note",
          "volume",
          "stock",
          "created_by",
          "updated_by",
          "created_at",
          "updated_at",
          "hidden",
          "spec"
        ]
      }]
    },
    "histories": {
      "title": "히스토리 목록",
      "type": "array",
      "items": [{
        "title": "히스토리",
        "type": "object",
        "properties": {
          "_id": {
            "title": "히스토리 id",
            "type": "string"
          },
          "version": {
            "title": "버전",
            "type": "string"
          },
          "basic_info": {
            "title": "기본정보",
            "type": "object",
            "properties": {
              "item_name": {
                "title": "품목명",
                "type": "string"
              },
              "usage": {
                "title": "사용유형",
                "type": "string"
              },
              "category": {
                "title": "카테고리",
                "type": "string"
              },
              "note": {
                "title": "메모",
                "type": "string"
              }
            },
            "required": [
              "item_name",
              "usage",
              "category",
              "note"
            ]
          },
          "contents": {
            "title": "구성품",
            "type": "array",
            "items": [{
              "type": "object",
              "properties": {
                "content_id": {
                  "title": "구성품 id",
                  "type": "string"
                },
                "content_index": {
                  "title": "구성품 순번",
                  "type": "string"
                },
                "content_name": {
                  "title": "구성품명",
                  "type": "string"
                },
                "note": {
                  "title": "특이사항",
                  "type": "string"
                },
                "volume": {
                  "title": "권장량",
                  "type": "integer"
                },
                "stock": {
                  "title": "재고",
                  "type": "integer"
                },
                "created_by": {
                  "title": "작성자",
                  "type": "string"
                },
                "updated_by": {
                  "title": "수정자",
                  "type": "string"
                },
                "created_at": {
                  "title": "작성일시",
                  "type": "string"
                },
                "updated_at": {
                  "title": "수정일시",
                  "type": "string"
                },
                "hidden": {
                  "title": "숨김",
                  "type": "boolean"
                },
                "spec": {
                  "title": "제품사양",
                  "type": "object",
                  "properties": {
                    "_id": {
                      "title": "object id",
                      "type": "string"
                    },
                    "spec_code": {
                      "title": "spec code",
                      "type": "string"
                    },
                    "custom": {
                      "title": "커스텀",
                      "type": "boolean"
                    },
                    "description": {
                      "title": "설명",
                      "type": "string"
                    },
                    "width": {
                      "title": "가로",
                      "type": "string"
                    },
                    "height": {
                      "title": "세로",
                      "type": "string"
                    },
                    "depth": {
                      "title": "높이",
                      "type": "string"
                    },
                    "material": {
                      "title": "재질",
                      "type": "string"
                    },
                    "print": {
                      "title": "인쇄",
                      "type": "string"
                    },
                    "processing": {
                      "title": "가공",
                      "type": "string"
                    },
                    "cost": {
                      "title": "제작단가",
                      "type": "integer"
                    },
                    "duration": {
                      "title": "소요기간",
                      "type": "integer"
                    },
                    "note": {
                      "title": "비고",
                      "type": "string"
                    },
                    "version": {
                      "title": "버전",
                      "type": "integer"
                    },
                    "shop": {
                      "title": "거래처",
                      "type": "object",
                      "properties": {
                        "shop_id": {
                          "title": "거래처 id",
                          "type": "string"
                        },
                        "shop_name": {
                          "title": "거래처 이름",
                          "type": "string"
                        }
                      },
                      "required": [
                        "shop_id",
                        "shop_name"
                      ]
                    }
                  },
                  "required": [
                    "_id",
                    "spec_code",
                    "custom",
                    "description",
                    "width",
                    "height",
                    "depth",
                    "material",
                    "print",
                    "processing",
                    "cost",
                    "duration",
                    "note",
                    "version",
                    "shop"
                  ]
                }
              },
              "required": [
                "content_id",
                "content_index",
                "content_name",
                "note",
                "volume",
                "stock",
                "created_by",
                "updated_by",
                "created_at",
                "updated_at",
                "hidden",
                "spec"
              ]
            }]
          },
          "created_by": {
            "title": "작성자",
            "type": "string"
          },
          "created_at": {
            "title": "작성일시",
            "type": "string"
          }
        },
        "required": [
          "_id",
          "version",
          "basic_info",
          "contents",
          "created_by",
          "created_at"
        ]
      }]
    },
    "hidden": {
      "title": "숨김",
      "type": "boolean"
    }
  },
  "required": [
    "item_id",
    "created_by",
    "updated_by",
    "created_at",
    "updated_at",
    "version",
    "basic_info",
    "contents",
    "histories",
    "hidden"
  ]
}

=== dooobob/json-schema-app/public/json/item.json
{
    "item_id": "",
    "created_by": "",
    "updated_by": "",
    "created_at": "",
    "updated_at": "",
    "version": "",
    "basic_info": {
        "item_name": "",
        "usage": "",
        "category": "",
        "note": ""
    },
    "contents": [{
        "content_id": "",
        "content_index": "",
        "content_name": "",
        "note": "",
        "volume": 0,
        "stock": 0,
        "created_by": "",
        "updated_by": "",
        "created_at": "",
        "updated_at": "",
        "hidden": false,
        "spec": {
            "_id": "",
            "spec_code": "",
            "custom": false,
            "description": "",
            "width": "",
            "height": "",
            "depth": "",
            "material": "",
            "print": "",
            "processing": "",
            "cost": 0,
            "duration": 0,
            "note": "",
            "version": 0,
            "created_by": "",
            "updated_by": "",
            "created_at": "",
            "updated_at": "",
            "shop": {
                "shop_id": "",
                "shop_name": ""
            }
        }
    }],
    "histories": [{
        "_id": "",
        "version": "",
        "basic_info": {
            "item_name": "",
            "usage": "",
            "category": "",
            "note": ""
        },
        "contents": [{
            "content_id": "",
            "content_index": "",
            "content_name": "",
            "note": "",
            "volume": 0,
            "stock": 0,
            "created_by": "",
            "updated_by": "",
            "created_at": "",
            "updated_at": "",
            "hidden": false,
            "spec": {
                "_id": "",
                "spec_code": "",
                "custom": false,
                "description": "",
                "width": "",
                "height": "",
                "depth": "",
                "material": "",
                "print": "",
                "processing": "",
                "cost": 0,
                "duration": 0,
                "note": "",
                "version": 0,
                "created_by": "",
                "updated_by": "",
                "created_at": "",
                "updated_at": "",
                "shop": {
                    "shop_id": "",
                    "shop_name": ""
                }
            }
        }],
        "created_by": "",
        "created_at": ""
    }],
    "hidden": true
}
