=== dooobob/json-schema-app/public/json/product_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "product_id": {
      "type": "string"
    },
    "custom": {
      "type": "boolean"
    },
    "product_version": {
      "type": "integer"
    },
    "created_by": {
      "type": "string"
    },
    "updated_by": {
      "type": "string"
    },
    "created_at": {
      "type": "string"
    },
    "updated_at": {
      "type": "string"
    },
    "basic_info": {
      "type": "object",
      "properties": {
        "product_name": {
          "type": "string"
        },
        "category": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "required": [
        "product_name",
        "category",
        "description"
      ]
    },
    "spec": {
      "type": "object",
      "properties": {
        "size": {
          "type": "string"
        },
        "material": {
          "type": "string"
        },
        "print": {
          "type": "string"
        },
        "processing": {
          "type": "string"
        }
      },
      "required": [
        "size",
        "material",
        "print",
        "processing"
      ]
    },
    "manufacture": {
      "type": "object",
      "properties": {
        "shop": {
          "type": "string"
        },
        "duration": {
          "type": "integer"
        },
        "cost": {
          "type": "integer"
        },
        "price": {
          "type": "integer"
        }
      },
      "required": [
        "shop",
        "duration",
        "cost",
        "price"
      ]
    },
    "items": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "item_id": {
              "type": "string"
            },
            "item_name": {
              "type": "string"
            },
            "logo_type": {
              "type": "string"
            },
            "volume": {
              "type": "integer"
            },
            "stock": {
              "type": "integer"
            }
          },
          "required": [
            "item_id",
            "item_name",
            "logo_type",
            "volume",
            "stock"
          ]
        }
      ]
    }
  },
  "required": [
    "product_id",
    "custom",
    "product_version",
    "created_by",
    "updated_by",
    "created_at",
    "updated_at",
    "basic_info",
    "spec",
    "manufacture",
    "items"
  ]
}

=== dooobob/json-schema-app/public/json/product.json
{
    "product_id": "",
    "custom": false,
    "product_version": 0,
    "created_by": "",
    "updated_by": "",
    "created_at": "",
    "updated_at": "",
    "basic_info":
    {
        "product_name": "",
        "category": "",
        "description": ""
    },
    "spec":
    {
        "size": "",
        "material": "",
        "print": "",
        "processing": ""
    },
    "manufacture":
    {
        "shop": "",
        "duration": 0,
        "cost": 0,
        "price": 0
    },
    "items":
    [
        {
            "item_id": "",
            "item_name": "",
            "logo_type": "",
            "volume": 0,
            "stock": 0
        }
    ]
}
